#!/bin/bash

# Copyright (C) 2010 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

if [ "${IMAGE_DEBUG}" = "1" ] ; then
    set -x
fi

. common.sh

# If the target device is not a real block device we'll first losetup it.
# This is needed for file disks.
if [ ! -b $blockdev ]; then
    ORIGINAL_BLOCKDEV=$blockdev
    blockdev=$($LOSETUP -sf $blockdev)
    CLEANUP+=("$LOSETUP -d $blockdev")
fi

format_disk0 $blockdev
filesystem_base_dev=$(map_disk0 $blockdev)
if [ "${SWAP}" = "yes" ] ; then
    boot_dev="${filesystem_base_dev}-1"
    swap_dev="${filesystem_base_dev}-2"
    root_dev="${filesystem_base_dev}-3"
else
    boot_dev="${filesystem_base_dev}-1"
    root_dev="${filesystem_base_dev}-2"
fi
CLEANUP+=("unmap_disk0 $blockdev")

vol_type_boot=$($VOL_TYPE $boot_dev)
vol_type_root=$($VOL_TYPE $root_dev)

if [ "$vol_type_boot" = "ext3" -o "$vol_type_boot" = "ext2" \
        -o "$vol_type_boot" = "ext4" ] ; then
    $DUMP -0 -q -f - "$boot_dev"
fi

if [ "$vol_type_root" = "ext3" -o "$vol_type_root" = "ext2" \
        -o "$vol_type_boot" = "ext4" ] ; then
    $DUMP -0 -q -f - "$boot_dev"
fi

# execute cleanups
cleanup
trap - EXIT

exit 0
