#!/bin/bash

# Copyright (C) 2010 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

. common.sh

debug set -x

# If the target device is not a real block device we'll first losetup it.
# This is needed for file disks.
if [ ! -b $blockdev ]; then
    ORIGINAL_BLOCKDEV=$blockdev
    blockdev=$($LOSETUP -sf $blockdev)
    CLEANUP+=("$LOSETUP -d $blockdev")
fi

filesystem_base_dev=$(map_disk0 $blockdev)
if [ "${SWAP}" = "yes" ] ; then
    boot_dev="${filesystem_base_dev}-1"
    swap_dev="${filesystem_base_dev}-2"
    root_dev="${filesystem_base_dev}-3"
else
    boot_dev="${filesystem_base_dev}-1"
    root_dev="${filesystem_base_dev}-2"
fi
CLEANUP+=("unmap_disk0 $blockdev")

vol_type_boot="$($VOL_TYPE $boot_dev)"
vol_type_root="$($VOL_TYPE $root_dev)"

for fs in boot root ; do
    # use indirect reference to make the variables dynamic
    dev="$(eval "echo \${$(echo ${fs}_dev)"})"
    vol_type="$(eval echo \$vol_type_${fs})"
    if [ -z "$vol_type" ] ; then
        log_error "Unable to find ${fs} filesystem type at ${dev}"
        exit 1
    fi
    if [ "$vol_type" = "ext3" -o "$vol_type" = "ext2" \
            -o "$vol_type" = "ext4" ] ; then
        $DUMP -0 -q -f - $dev | gzip ${TARGET}/${fs}.dump.gz
        CLEANUP+=("rm ${TARGET}/${fs}.dump.gz")
    else
        log_error "${fs} is not a supported filesystem. Please use ext{2,3,4}"
        exit 1
    fi
done

( cd $TARGET ; tar -cf - . )

# execute cleanups
cleanup
trap - EXIT

exit 0
