#!/bin/bash

# Copyright (C) 2010 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

. common.sh

debug set -x

# If the target device is not a real block device we'll first losetup it.
# This is needed for file disks.
if [ ! -b $blockdev ]; then
    ORIGINAL_BLOCKDEV=$blockdev
    blockdev=$($LOSETUP -sf $blockdev)
    CLEANUP+=("$LOSETUP -d $blockdev")
fi

format_disk0 $blockdev
filesystem_base_dev=$(map_disk0 $blockdev)
if [ "${SWAP}" = "yes" ] ; then
    boot_dev="${filesystem_base_dev}-1"
    swap_dev="${filesystem_base_dev}-2"
    root_dev="${filesystem_base_dev}-3"
else
    boot_dev="${filesystem_base_dev}-1"
    root_dev="${filesystem_base_dev}-2"
fi
CLEANUP+=("unmap_disk0 $blockdev")

mkfs_disk0 $boot_dev $root_dev $swap_dev

TARGET=`mktemp -d` || exit 1
CLEANUP+=("rmdir $TARGET")
DUMPDIR=`mktemp -d` || exit 1
CLEANUP+=("rm -rf $DUMPDIR")

mount_disk0 $TARGET $root_dev $boot_dev

# import dumps from tar file
( cd $DUMPDIR; tar -zxf - )
( cd $TARGET ; gunzip -c ${DUMPDIR}/root.dump.gz | restore -r -y -f - )
( cd ${TARGET}/boot ; gunzip -c ${DUMPDIR}/boot.dump.gz | restore -r -y -f - )

rm -f $TARGET/etc/udev/rules.d/z*_persistent-net.rules

if [ -n "$CUSTOMIZE_DIR" -a -d "$CUSTOMIZE_DIR" -a -x "$CUSTOMIZE_DIR/grub" ] ; then
    TARGET=$TARGET
    BLOCKDEV=$blockdev
    ROOT_DEV=$root_dev
    BOOT_DEV=$boot_dev
    IMPORT_SCRIPT="1"
    export TARGET SUITE BLOCKDEV ROOT_DEV BOOT_DEV IMPORT_SCRIPT
    # Install grub since we're not deploying via qemu-img
    ${CUSTOMIZE_DIR}/grub
fi

# execute cleanups
cleanup
trap - EXIT

exit 0
