name             'instance-image-devel'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Installs/Configures instance-image-devel'
version          '0.1.0'
depends          'ganeti'
depends          'line'
