#!/bin/bash

# Copyright (C) 2010 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# This is an example script that configures your network settings after
# installation. By default it sets it up to use dhcp.

set -e

. common.sh

if [ "${IMAGE_DEBUG} " = 1 ] ; then
    set -x
fi

DIG="$(which dig)"

# discover fqdn name using dig
if [ -n "$NIC_0_IP" -a -n "${DIG}" ] ; then
    FQDN="$(${DIG} -x ${NIC_0_IP} +short | sed -e 's/\.$//')"
fi

if [ -z "${TARGET}" -o ! -d "${TARGET}" ] ; then
    log_error "Missing target directory"
    exit 1
fi

if [ -z "${NIC_COUNT}" ] ; then
    log_error "Missing NIC_COUNT"
    exit 1
fi

# Functions
debian_setup() {
    if [ ! -d "${TARGET}/etc/network" ] ; then
        log_error "Missing target network directory"
        exit 1
    fi
    cat > ${TARGET}/etc/network/interfaces << EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

EOF

    if [ -n "${FQDN}" ] ; then
        echo "${FQDN}" > ${TARGET}/etc/hostname
    fi
}

redhat_setup() {
    if [ ! -d "${TARGET}/etc/sysconfig/network-scripts" ] ; then
        log_error "Missing target network directory"
        exit 1
    fi
    cat > ${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0 << EOF
DEVICE=eth0
BOOTPROTO=dhcp
HWADDR=${NIC_0_MAC^^[a-z]}
ONBOOT=yes
EOF

    if [ -n "${FQDN}" ] ; then
        cat > ${TARGET}/etc/sysconfig/network << EOF
NETWORKING=yes
HOSTNAME=${FQDN}
EOF
    else
        cat > ${TARGET}/etc/sysconfig/network << EOF
NETWORKING=yes
EOF
    fi
}

gentoo_setup() {
    if [ ! -f "${TARGET}/etc/conf.d/net" ] ; then
        log_error "Missing target network file"
        exit 1
    fi
    cat > ${TARGET}/etc/conf.d/net << EOF
config_eth0=( "dhcp" )
EOF
    chroot ${TARGET} rc-update add net.eth0 default

    if [ -n "${FQDN}" ] ; then
        cat > ${TARGET}/etc/conf.d/hostname << EOF
HOSTNAME="${FQDN}"
EOF
    fi
}

suse_setup() {
    if [ ! -d ${TARGET}/etc/sysconfig/network ] ; then
        log_error "Missing target network directory"
        exit 1
    fi
    cat > ${TARGET}/etc/sysconfig/network/ifcfg-eth0 << EOF
BOOTPROTO='dhcp4'
LLADDR='${NIC_0_MAC^^[a-z]}'
STARTMODE='auto'
NAME='Ethernet Card 0'
EOF
    if [ -n "${FQDN}" ] ; then
        echo "${FQDN}" > ${TARGET}/etc/HOSTNAME
    fi
}

# Main
get_os_type

if [ "${NIC_COUNT}" -gt 0 -a -n "${OS_TYPE}" ] ; then
    ${OS_TYPE}_setup
else
    log_error "Unsupported OS_TYPE"
fi


exit 0
