#!/bin/bash

# Remove all generated keys so that each instance has unique keys for ssh

set -e

. common.sh

if [ "${IMAGE_DEBUG} " = 1 ] ; then
    set -x
fi

if [ -e ${TARGET}/etc/debian_version ] ; then
    echo "Debian/Ubuntu create keys at install time, skipping"
    exit 0
fi

HOST_KEY="/etc/ssh/ssh_host_key"
RSA_KEY="/etc/ssh/ssh_host_rsa_key"
DSA_KEY="/etc/ssh/ssh_host_dsa_key"

for key in $HOST_KEY $RSA_KEY $DSA_KEY ; do
    if [ -f "${TARGET}/${key}" ] ; then
        rm -f ${TARGET}/${key}
    fi
done

exit 0
