#!/bin/bash

# Remove all generated keys so that each instance has unique keys for ssh

. common.sh

if [ "${DEBUG_LEVEL} " = 1 ] ; then
    set -x
fi

HOST_KEY="/etc/ssh/ssh_host_key"
RSA_KEY="/etc/ssh/ssh_host_rsa_key"
DSA_KEY="/etc/ssh/ssh_host_dsa_key"

for key in $HOST_KEY $RSA_KEY $DSA_KEY ; do
    if [ -f "${TARGET}/${key}" ] ; then
        rm -f ${TARGET}/${key}
    fi
done

exit 0
