#!/bin/bash
set -e
INSTANCE_NAME="$1"

if [ -z "$INSTANCE_NAME" ] ; then
    echo "Must provide a node name!"
    exit 1
fi

info=($(gnt-instance list -o os,hypervisor,disk.count --no-headers --separator=' ' $INSTANCE_NAME))
OS_VARIANT="${info[0]/*+/}"
HYPERVISOR="${info[1]}"
DISK_COUNT="${info[2]}"
OS_API_VERSION="15"

# do stuff
output="$(gnt-instance activate-disks $INSTANCE_NAME)"
CLEANUP+=("gnt-instance deactivate-disks $INSTANCE_NAME")

DISK_0_PATH="${output/*disk\/0\:/}"

. /usr/share/ganeti/os/image/common.sh

if [ -n "$2" ] ; then
    IMAGE_DIR=$2
fi

echo "Creating qemu-img image from $INSTANCE_NAME to ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img"
$QEMU_IMG convert -O qcow2 $DISK_0_PATH ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img
