#!/bin/bash

# Copyright (C) 2015 Oregon State University
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
# Copy files from an overlay directory into an instance. This assumes the same
# filesystem structure as the system.

set -e

. common.sh

# Ganeti specific NoCloud cloud-init config
cinit_cfg="/etc/cloud/cloud.cfg.d/99_ganeti.cfg"

debug set -x

if [ -z "${TARGET}" -o ! -d "${TARGET}" ] ; then
    log_error "Missing target directory"
    exit 1
fi

# Need to export these out to the ruby script can read it
export CINIT_USER CINIT_SSH_KEY CINIT_SSH_PWAUTH
export CINIT_MANAGE_RESOLV_CONF CINIT_DISABLE_ROOT
export DNS_SERVERS DNS_SEARCH

# Write out config as a yaml file
if [ -d ${TARGET}/etc/cloud/cloud.cfg.d ] ; then
  ./cloud_init.rb > ${TARGET}/${cinit_cfg}
else
  log_error "cloud-init is not installed"
  exit 1
fi

exit 0
